name:    hs-pdfkit
version: 0.0.1

category: Graphics
description: PdfKit renders Pdf documents with a monadic API that is still very limited.
extra-source-files:
  - CHANGELOG.md
  - package.yaml
  - README.md
  - stack.yaml
github: agreif/hs-pdfkit
license-file: LICENSE.md
license: MIT
maintainer: Alex Greif
synopsis: Render PDF files with a monadic api.

dependencies:
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
- aeson
- text
- bytestring
- time
- hex
- microlens-platform
- filepath
- directory

data-files:
- Core14_AFMs/Courier-Bold.afm
- Core14_AFMs/Helvetica-BoldOblique.afm
- Core14_AFMs/Times-Bold.afm
- Core14_AFMs/Courier-BoldOblique.afm
- Core14_AFMs/Helvetica-Oblique.afm
- Core14_AFMs/Times-BoldItalic.afm
- Core14_AFMs/Courier-Oblique.afm
- Core14_AFMs/Helvetica.afm
- Core14_AFMs/Times-Italic.afm
- Core14_AFMs/Courier.afm
- Core14_AFMs/MustRead.html
- Core14_AFMs/Times-Roman.afm
- Core14_AFMs/Helvetica-Bold.afm
- Core14_AFMs/Symbol.afm
- Core14_AFMs/ZapfDingbats.afm



library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0

flags:
  library-only:
    default: false
    manual: false
